package com.ursuradu.maze;

import static com.ursuradu.maze.MazeConfigPreset.Constants.*;
import static com.ursuradu.maze.enums.MazeDrawStyle.*;
import static com.ursuradu.maze.enums.PathRequirements.CONTAIN_ALL_PORTALS;
import static com.ursuradu.maze.model.OnTheFlyPortals.*;
import static java.util.Collections.emptyList;
import static java.util.List.of;

import com.ursuradu.maze.config.MazeConfig;

public enum MazeConfigPreset {

  SMALL_CLASSIC_NO_PORTALS(1, new MazeConfig("PRESET-1", SMALL_SIZE, SMALL_SIZE, CLASSIC, 0, DISABLED, emptyList())),
  SMALL_BRIDGES_NO_PORTALS(2, new MazeConfig("PRESET-2", SMALL_SIZE, SMALL_SIZE, PIPES_BRIDGES, 0, DISABLED, emptyList())),

  SMALL_CLASSIC_1_PORTAL(3, new MazeConfig("PRESET-3", SMALL_SIZE, SMALL_SIZE, CLASSIC, 1, DISABLED, emptyList())),
  SMALL_PIPES_BRIDGES_1_PORTAL(4, new MazeConfig("PRESET-4", SMALL_SIZE, SMALL_SIZE, PIPES_BRIDGES, 1, DISABLED, emptyList())),

  SMALL_CLASSIC_1_PORTAL_EASY(5, new MazeConfig("PRESET-5", SMALL_SIZE, SMALL_SIZE, CLASSIC, 1, DISABLED, of(CONTAIN_ALL_PORTALS))),
  SMALL_PIPES_BRIDGES_1_PORTAL_EASY(6, new MazeConfig("PRESET-6", SMALL_SIZE, SMALL_SIZE, PIPES_BRIDGES, 1, DISABLED, of(CONTAIN_ALL_PORTALS))),

  SMALL_CLASSIC_3_PORTAL(7, new MazeConfig("PRESET-7", SMALL_SIZE, SMALL_SIZE, CLASSIC, 3, DISABLED, emptyList())),
  SMALL_PIPES_BRIDGES_3_PORTAL(8, new MazeConfig("PRESET-8", SMALL_SIZE, SMALL_SIZE, PIPES_BRIDGES, 3, DISABLED, emptyList())),

  SMALL_CLASSIC_3_PORTAL_EASY(9, new MazeConfig("PRESET-9", SMALL_SIZE, SMALL_SIZE, CLASSIC, 3, DISABLED, of(CONTAIN_ALL_PORTALS))),
  SMALL_PIPES_BRIDGES_3_PORTAL_EASY(10, new MazeConfig("PRESET-10", SMALL_SIZE, SMALL_SIZE, PIPES_BRIDGES, 3, DISABLED, of(CONTAIN_ALL_PORTALS))),

  MEDIUM_CLASSIC_NO_PORTALS(11, new MazeConfig("PRESET-11", MEDIUM_SIZE, MEDIUM_SIZE, CLASSIC, 0, DISABLED, emptyList())),
  MEDIUM_PIPES_BRIDGES_NO_PORTALS(12, new MazeConfig("PRESET-12", MEDIUM_SIZE, MEDIUM_SIZE, PIPES_BRIDGES, 0, DISABLED, emptyList())),

  MEDIUM_CLASSIC_1_PORTAL(13, new MazeConfig("PRESET-13", MEDIUM_SIZE, MEDIUM_SIZE, CLASSIC, 1, DISABLED, emptyList())),
  MEDIUM_PIPES_BRIDGES_1_PORTAL(14, new MazeConfig("PRESET-14", MEDIUM_SIZE, MEDIUM_SIZE, PIPES_BRIDGES, 1, DISABLED, emptyList())),

  MEDIUM_CLASSIC_7_PORTAL_EASY(15, new MazeConfig("PRESET-15", MEDIUM_SIZE, MEDIUM_SIZE, CLASSIC, 7, DISABLED, of(CONTAIN_ALL_PORTALS))),
  MEDIUM_PIPES_BRIDGES_7_PORTAL_EASY(16, new MazeConfig("PRESET-16", MEDIUM_SIZE, MEDIUM_SIZE, PIPES_BRIDGES, 7, DISABLED, of(CONTAIN_ALL_PORTALS))),

  MEDIUM_CLASSIC_5_PORTAL(17, new MazeConfig("PRESET-17", MEDIUM_SIZE, MEDIUM_SIZE, CLASSIC, 5, DISABLED, emptyList())),
  MEDIUM_PIPES_BRIDGES_5_PORTAL(18, new MazeConfig("PRESET-18", MEDIUM_SIZE, MEDIUM_SIZE, PIPES_BRIDGES, 5, DISABLED, emptyList())),

  MEDIUM_CLASSIC_5_PORTAL_EASY(19, new MazeConfig("PRESET-19", MEDIUM_SIZE, MEDIUM_SIZE, CLASSIC, 5, DISABLED, of(CONTAIN_ALL_PORTALS))),
  MEDIUM_PIPES_BRIDGES_5_PORTAL_EASY(20, new MazeConfig("PRESET-20", MEDIUM_SIZE, MEDIUM_SIZE, PIPES_BRIDGES, 5, DISABLED, of(CONTAIN_ALL_PORTALS))),

  LARGE_CLASSIC_NO_PORTALS(21, new MazeConfig("PRESET-21", LARGE_SIZE, LARGE_SIZE, CLASSIC, 0, DISABLED, emptyList())),
  LARGE_PIPES_BRIDGES_NO_PORTALS(22, new MazeConfig("PRESET-22", LARGE_SIZE, LARGE_SIZE, PIPES_BRIDGES, 0, DISABLED, emptyList())),

  LARGE_CLASSIC_1_PORTAL(23, new MazeConfig("PRESET-23", LARGE_SIZE, LARGE_SIZE, CLASSIC, 1, DISABLED, emptyList())),
  LARGE_PIPES_BRIDGES_1_PORTAL(24, new MazeConfig("PRESET-24", LARGE_SIZE, LARGE_SIZE, PIPES_BRIDGES, 1, DISABLED, emptyList())),

  LARGE_CLASSIC_10_PORTAL_EASY(25, new MazeConfig("PRESET-25", LARGE_SIZE, LARGE_SIZE, CLASSIC, 10, DISABLED, of(CONTAIN_ALL_PORTALS))),
  LARGE_PIPES_BRIDGES_10_PORTAL_EASY(26, new MazeConfig("PRESET-26", LARGE_SIZE, LARGE_SIZE, PIPES_BRIDGES, 10, DISABLED, of(CONTAIN_ALL_PORTALS))),

  LARGE_CLASSIC_5_PORTAL(27, new MazeConfig("PRESET-27", LARGE_SIZE, LARGE_SIZE, CLASSIC, 5, DISABLED, emptyList())),
  LARGE_PIPES_BRIDGES_5_PORTAL(28, new MazeConfig("PRESET-28", LARGE_SIZE, LARGE_SIZE, PIPES_BRIDGES, 5, DISABLED, emptyList())),

  LARGE_CLASSIC_5_PORTAL_EASY(29, new MazeConfig("PRESET-29", LARGE_SIZE, LARGE_SIZE, CLASSIC, 5, LARGE_RATE, emptyList())),
  LARGE_PIPES_BRIDGES_5_PORTAL_EASY(30, new MazeConfig("PRESET-30", LARGE_SIZE, LARGE_SIZE, PIPES_BRIDGES, 5, LARGE_RATE, emptyList()));

  private final int id;
  private final MazeConfig mazeConfig;

  MazeConfigPreset(final int id, final MazeConfig mazeConfig) {
    this.id = id;
    this.mazeConfig = mazeConfig;
  }

  public int getId() {
    return id;
  }

  public MazeConfig getMazeConfig() {
    return mazeConfig;
  }

  public static class Constants {

    public static final int SMALL_SIZE = 10;
    public static final int MEDIUM_SIZE = 13;
    public static final int LARGE_SIZE = 16;
  }
}
